// Every photo in public/images has a light "<name>-800.webp" next to it
// (generated by scripts/optimize-images.py). Use it for cards and thumbnails;
// keep the full file for large views.
const LOCAL_PHOTO = /^\/images\/.+\.(jpe?g|png)$/i;

export const thumb = (src: string) => {
  if (LOCAL_PHOTO.test(src)) return src.replace(/\.(jpe?g|png)$/i, '-800.webp');
  if (src.includes('images.unsplash.com')) return withUnsplashWidth(src, 800);
  return src;
};

// srcSet for large images: phones get the 800 px version, bigger screens the full one.
export const photoSrcSet = (src: string) => {
  if (LOCAL_PHOTO.test(src)) return `${thumb(src)} 800w, ${src} 1920w`;
  if (src.includes('images.unsplash.com')) {
    return [800, 1280, 1920].map((w) => `${withUnsplashWidth(src, w)} ${w}w`).join(', ');
  }
  return undefined;
};

const withUnsplashWidth = (src: string, w: number) => {
  const url = new URL(src);
  url.searchParams.set('w', String(w));
  url.searchParams.set('auto', 'format');
  url.searchParams.set('q', '75');
  return url.toString();
};
